name: mosul_scanner
description: Mosul Scanner App
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.3
  image: ^4.1.7
  pdf: ^3.10.8
  printing: ^5.11.1
ffi: ^2.1.3
  google_mlkit_document_scanner: ^0.5.0

  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
