name: mosul_scanner
description: "A professional document scanning and printing application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # تأكد من توافق إصدار الـ SDK مع نسختك

dependencies:
  flutter:
    sdk: flutter

  # واجهة المستخدم الأساسية
  cupertino_icons: ^1.0.6

  # مكتبات معالجة الصور
  image: ^4.1.7
  
  # مكتبة جلب الصور من الكاميرا أو المعرض
  image_picker: ^1.1.2
  
  # مكتبات إنشاء وطباعة ملفات الـ PDF
  pdf: ^3.11.1
  printing: ^5.12.0

  # الذكاء الاصطناعي واكتشاف حواف المستندات (القص التلقائي)
  opencv_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # إذا كان لديك أي ملفات أو صور داخل التطبيق (Assets)، يمكنك إضافتها هنا مستقبلاً
  # assets:
  #   - assets/images/
